# Generated by Django 6.0.7 on 2026-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, help_text='Optional, e.g. "19.5h"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('date_range', models.CharField(max_length=100)),
                ('cgpa', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('date_range', models.CharField(max_length=100)),
                ('bullets', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the name, e.g. "// full-stack developer"', max_length=100)),
                ('pitch', models.TextField(help_text='One or two sentence hero tagline.')),
                ('status', models.CharField(default='open_to_work', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('graduating', models.CharField(blank=True, max_length=50)),
                ('cgpa', models.CharField(blank=True, max_length=20)),
                ('focus_area', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('about', models.JSONField(default=list, help_text='List of About-section paragraphs, in order.')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=250)),
                ('icon', models.CharField(choices=[('lock', 'Lock (security / auth)'), ('waveform', 'Waveform (audio / signal)')], default='lock', max_length=20)),
                ('tech_stack', models.JSONField(default=list, help_text='List of tech tag strings.')),
                ('bullets', models.JSONField(default=list, help_text='List of description bullet strings.')),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(default=list, help_text='List of skill name strings, e.g. ["Python", "JavaScript"]')),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
