# Generated by Django 6.0.7 on 2026-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('lock', 'Lock (security / auth)'), ('waveform', 'Waveform (audio / signal)'), ('leaf', 'Leaf (environment / ML)')], default='lock', max_length=20),
        ),
    ]
