# Generated by Django 6.0.7 on 2026-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Optional link to the certificate.'),
        ),
    ]
