# Generated by Django 6.0.7 on 2026-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certification_certificate_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
